name: pokedex
description: "A Pokedex app for displaying details about Pokemon"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  graphql_flutter: ^5.2.0-beta.8
  http: ^1.3.0
  json_annotation: ^4.8.1
  lucide_icons: ^0.257.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
