name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [main, master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "beta"

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter packages get

      - name: Build web
        run: flutter build web --base-href '/pokedex/'
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          user_name: "github-actions"
          user_email: "github-actions@github.com"
